spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eletroshop?autoreconnect=true
    username: ${USERNAME_BD}
    password: ${PASSWORD_BD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource 
    hikari:
      connection-timeout: 2000 #numéro máx de milisegundos que um cliente aguardará por uma conexão
      minimum-idle: 200 #numéro mín de conexões inativa pelo HikariCP em um conjunto de conexões
      maximum-pool-size: 550 #máx de pool de conexão
      idle-timeout: 10000 #tempo ocioso de conexão
      pool-name: PoolHikari
      auto-commit: false
    dbcp2:
      pool-prepared-statements: true #processos e execuções no bd
      max-open-prepared-statements: 550 #numero de portas abertas para processos de conexões e execuções de sql no bd
  
  session:
    jdbc:
      cleanup-cron: 0 0 4 * * * #limpar sugeras no bd de seções, commits, transactions não utilizados a cada 4h

  transaction:
    rollback-on-commit-failure: true #caso dê problemas nas transactions para manter a integridade dos dados

  mvc:
    static-path-pattern: /resources/static/** #permição que o spring security não bloquei

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

        
  servlet: 
    multipart:
      enabled: true
      max-file-size: 10000KB
      max-request-size: 10000KB    
     

server: #config modo de compressão da aplicação
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  servlet: #config charset da aplicação
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
    session:
      timeout: 240m #tempo de duração da sessão
  tomcat:
    max-connections: 50000 #numero máx de conexões no servidor
    threads:
      min-spare: 1000 #melhora de performance do tomcat