SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'eletroshop' AND TABLE_NAME = 'user_access'
and CONSTRAINT_NAME <> 'unique_role_access_user' and CONSTRAINT_TYPE <> 'FOREIGN KEY';

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'eletroshop' AND TABLE_NAME = 'user_access'
and CONSTRAINT_NAME = 'unique_role_access_user' ;

ALTER TABLE USER_ACCESS DROP FOREIGN KEY role_access_id;
ALTER TABLE USER_ACCESS DROP INDEX `UK_p0ygtmlbxff8x3twqr6fgt1a8`;
